spring:
  datasource:
    url: jdbc:h2:mem:courierdb
    driver-class-name: org.h2.Driver
    username: admin
    password: ps
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080 